version: '3.1'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api-activity-db
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.pl
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGDATA: /var/lib
    ports:
      - "5050:80"
    restart: always
  app:
    image: 'currency-calculator'
    container_name: currency-calculator-app
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/api-activity-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update